[Climate]
bDaylightSavings = 0	; When set to 1, the amount of daylight each day is dependent on the season, and where in between seasons you sit. 
						; Summer days are the longest, winter days are the shortest, the first day of summer is longer than the middle day of summer, etc.
						; How noticable is it? Not very. Why did I include it? Because I have an autistic level of attention to detail.
						; Set it to 0 to disable this feature, I wouldn't blame you... or would I?

; The following two events are hardcoded. This is because they fall on different days each year.

[Events]
bThanksgiving = 1		; Thanksgiving takes place always takes place on the 4th Thursday of November.
bEaster=1				; Easter falls on the first Sunday after the first full moon that occurs on or after the vernal equinox.